services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/html/site1:/usr/share/nginx/html/site1
      - ./nginx/html/site2:/usr/share/nginx/html/site2
