#!/bin/bash

for line in $(cat functions.txt); do
    echo '#include <stdio.h>' > $line.c > /home/user/Desktop/output_file.txt

    while read line;
    do
        echo "$line" >> $line.c
    done < "prototypes.txt"
    echo 'int main()' >> $line.c
    echo '{' >> $line.c
    echo '//code here' >> $line.c
    echo 'return 0;' >> $line.c
done
