services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
